[package]
name = "infinite-rs"
version = "0.2.2"
edition = "2021"
authors = ["Surasia"]
license = "Unlicense OR MIT"
repository = "https://github.com/Surasia/infinite-rs"
documentation = "https://docs.rs/infinite-rs"
description = "Simple and fast deserialization library for Halo Infinite."
categories = ["encoding", "games", "parsing"]
keywords = ["halo", "halo-infinite", "game-hacking", "reverse-engineering"]

[dependencies]
anyhow = "1.0.87"
bitflags = "2.6.0"
byteorder = "1.5.0"
num_enum = "0.7.3"
thiserror = "1.0.63"
walkdir = "2.5.0"

[build-dependencies.cmake]
version = "0.1"
