name: Cargo test/clippy/build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        profile: ["release", "dev"]
    steps:
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2.6
      
      - name: Install latest rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2.7.5
      
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build
        run: cargo build --verbose --profile ${{ matrix.profile }}
      
      - name: Run tests
        run: cargo test --verbose --profile ${{ matrix.profile }}
      
      - name: Check clippy
        run: cargo clippy --all-targets --all-features
